#!/usr/bin/env Rscript
# Documentation freshness. Regenerates with roxygen2 and fails if anything moves.
#
# This is the guard for the ORIGINAL bug in this repo: NAMESPACE was maintained
# by hand, drifted from the @export tags, and three tagged exports silently never
# shipped. Committed man/ and NAMESPACE must be exactly what the sources produce.
if (!requireNamespace("roxygen2", quietly = TRUE))
  stop("check_docs_fresh.R needs roxygen2", call. = FALSE)

# Roxygen output is VERSION DEPENDENT -- 8.0.0 writes one importFrom() per line
# where a newer roxygen collapses them into a multi-line call. Regenerating with
# a different version therefore produces a diff that says nothing about the
# sources. DESCRIPTION's Config/roxygen2/version records which version produced
# the committed man/ and NAMESPACE; refuse to compare against any other, and say
# so plainly rather than emitting a confusing diff.
# unname/trimws: read.dcf returns a NAMED character, and identical() would
# compare the names too and always report a mismatch.
want <- tryCatch(trimws(unname(read.dcf("DESCRIPTION")[1, "Config/roxygen2/version"])),
                 error = function(e) NA_character_)
have <- as.character(utils::packageVersion("roxygen2"))
if (is.na(want)) {
  message("FAIL: DESCRIPTION has no Config/roxygen2/version, so doc regeneration ",
          "is not reproducible. Run roxygen2::roxygenise() once and commit.")
  quit(status = 1L, save = "no")
}
if (!identical(want, have)) {
  message("FAIL: roxygen2 version mismatch.\n",
          "  committed docs were generated by: ", want, "\n",
          "  this environment has:             ", have, "\n",
          "Install the pinned version, or regenerate with the newer roxygen2 and\n",
          "commit both the docs and the updated Config/roxygen2/version.")
  quit(status = 1L, save = "no")
}
cat("roxygen2 ", have, " matches Config/roxygen2/version\n", sep = "")

before <- system2("git", c("status", "--porcelain", "man", "NAMESPACE"), stdout = TRUE)
if (length(before))
  message("NOTE: man/ or NAMESPACE was already dirty before regeneration:\n",
          paste(before, collapse = "\n"))

roxygen2::roxygenise(".")

diff <- system2("git", c("status", "--porcelain", "man", "NAMESPACE"), stdout = TRUE)
if (length(diff)) {
  message("FAIL: regenerating docs changed committed files. Run:\n",
          "  Rscript -e 'roxygen2::roxygenise()'\nand commit the result.\n")
  message(paste(diff, collapse = "\n"))
  system2("git", c("--no-pager", "diff", "--", "man", "NAMESPACE"))
  quit(status = 1L, save = "no")
}
cat("man/ and NAMESPACE are in sync with the sources\n")
